// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import type { Chain } from 'viem/chains'
import {
  base,
  baseSepolia,
  mainnet,
  optimism,
  optimismSepolia,
  pgn,
  pgnTestnet,
  sepolia,
  zora,
  zoraSepolia,
} from 'viem/chains'

import type { NetworkPairGroup } from '../types'
import { lyra, mode, orderlyNetwork } from './chains'

// clone of mainnet and edit the chainId
const quicknodeETHSepolia: Chain = {
  ...sepolia,
  name: 'quicknodeETHSepolia',
  rpcUrls: {
    default: {
      http: [
        'https://omniscient-sparkling-model.ethereum-sepolia.quiknode.pro/0650b5f675a2d17b00c8aa2a29dadc3e46f7fdbb/',
      ],
    },
  },
}
const quicknodeOPMainnet: Chain = {
  ...optimismSepolia,
  name: 'quicknodeOPMainnet',
  rpcUrls: {
    default: {
      http: [
        'https://dimensional-purple-mountain.optimism-sepolia.quiknode.pro/44f0d61844a6b6e40d2c2408aef2a4dd4df22f83/',
      ],
    },
  },
}

export type NetworkType =
  | 'base'
  | 'lyra'
  | 'mode'
  | 'op'
  | 'orderly'
  | 'pgn'
  | 'zora'
  | 'quicknode'

export const networkPairsByGroup: NetworkPairGroup = {
  base: {
    mainnet: [mainnet, base],
    sepolia: [sepolia, baseSepolia],
  },
  lyra: {
    mainnet: [mainnet, lyra],
  },
  mode: {
    mainnet: [mainnet, mode],
  },
  op: {
    mainnet: [mainnet, optimism],
    sepolia: [sepolia, optimismSepolia],
  },
  orderly: {
    mainnet: [mainnet, orderlyNetwork],
  },
  pgn: {
    mainnet: [mainnet, pgn],
    sepolia: [sepolia, pgnTestnet],
  },
  zora: {
    mainnet: [mainnet, zora],
    sepolia: [sepolia, zoraSepolia],
  },
  quicknode: {
    mainnet: [mainnet, optimism],
    sepolia: [quicknodeETHSepolia, quicknodeOPMainnet],
  },
}

export const networkPairsByID: Record<number, [Chain, Chain]> = {
  8453: [mainnet, base],
  957: [mainnet, lyra],
  34443: [mainnet, mode],
  10: [mainnet, optimism],
  291: [mainnet, orderlyNetwork],
  424: [mainnet, pgn],
  7777777: [mainnet, zora],
  84532: [sepolia, baseSepolia],
  11155420: [sepolia, optimismSepolia],
  58008: [sepolia, pgnTestnet],
  999999999: [sepolia, zoraSepolia],
}
